### ISSUE TITLE
[1.20.1+1.19.2] Generation errors

### ISSUE THREAD

**Issue by Reshy** [decodinatorX/Liroth-Revamped-Forge#27] opened 2023-11-06 07:04 UTC
Grass is spawning under water in the Jalsphire Plains and in Liroth, causing cascades of chunk updates when the dimensions get loaded:

![2023-11-05_23 00 16](https://github.com/decodinatorX/Liroth-Revamped-Forge/assets/2096384/8001bd1e-b56c-4b45-8059-216cdf2263b5)
![2023-11-01_17 26 09](https://github.com/decodinatorX/Liroth-Revamped-Forge/assets/2096384/65b5661a-7568-4571-8406-a37fe5192a59)

Vines are spawning floating in mid air in Damnation:
![2023-11-05_22 55 24](https://github.com/decodinatorX/Liroth-Revamped-Forge/assets/2096384/e0fc4c5b-b2c3-49b5-b1c8-dbc1866055a3)

**Comment by decodinatorX** [comment] 2024-06-21 12:20
Screenshots one and two were caused by incorrect noise settings for the water checks
Screenshot three was caused by the feature having an incorrect block (in this case: air) being an allowed block to be placed on

Both of these are fixed in the dev build and will be pushed out to version 1.19.2 through 1.20.1 soon.
![2024-06-21_08 18 22](https://github.com/decodinatorX/Liroth-Revamped-Forge/assets/16389833/2cea31d6-0cb9-46af-93fd-011859b7638b)
![2024-06-21_08 18 45](https://github.com/decodinatorX/Liroth-Revamped-Forge/assets/16389833/3088f805-c0ca-4b7f-a3a4-dbb79f7d4c16)
![2024-06-21_08 19 15](https://github.com/decodinatorX/Liroth-Revamped-Forge/assets/16389833/922c5688-f993-467a-b10c-7ae47b895d21)

**Comment by decodinatorX** [comment] 2024-06-21 12:20
Thank you for your patience and your report! They are greatly appreciated!

**Comment by decodinatorX** [comment] 2024-06-23 13:32
Latest build fixes this issue!

**Closed as completed by decodinatorX** 2024-06-23 13:32 UTC
Labels: bug
