### ISSUE TITLE
Rendering Errors

### ISSUE THREAD

**Issue by Reshy** [decodinatorX/Liroth-Revamped-Forge#28] opened 2023-11-06 07:27 UTC
The mod has some rendering errors:

Z-Fighting on the Prowler's Face:
![2023-11-05_23 09 29](https://github.com/decodinatorX/Liroth-Revamped-Forge/assets/2096384/b3cc2d66-fbc2-40a9-9e2d-c004f9447c2e)

Z-Fighting on Pier Peep's tentacles:
![2023-11-05_23 24 32](https://github.com/decodinatorX/Liroth-Revamped-Forge/assets/2096384/4ec978d3-4dbd-4e49-ab07-fb50aa32a69d)

Z-Fighting on Skeletal Freak's 'glowy bits' and certain bones:
![2023-11-05_23 23 59](https://github.com/decodinatorX/Liroth-Revamped-Forge/assets/2096384/9b3803ad-52a1-49be-9cb0-b4a14731f6e7)
![2023-11-05_23 24 01](https://github.com/decodinatorX/Liroth-Revamped-Forge/assets/2096384/b42bbad3-dc52-401f-b8cc-9f66c862ee07)

Jalsphire Crystal Blocks are rendering when surrounded by other Jalsphire crystal blocks:
![2023-11-05_23 09 11](https://github.com/decodinatorX/Liroth-Revamped-Forge/assets/2096384/5f8be814-da1e-49a3-ad1d-25405ab11abb)

Anomaly Blocks are rendering when surrounded by other Anomaly Blocks:
![2023-11-05_23 16 02](https://github.com/decodinatorX/Liroth-Revamped-Forge/assets/2096384/847013fd-b37d-4348-8b88-96e4e7771322)

**Comment by decodinatorX** [comment] 2024-06-21 12:27
Bare with me as I do this in a weird order:
The LAST two screenshots were caused by both having no occlusion on, in the Anomaly Block's case, that was my bad, in the Jalsphire Crystal Block, because it copied the Glass block (simply cause I wanted it to break easy, not drop itself, AND have the glass sounds) it copied the no occlusion setting as well.

The Z-Fighting on every entity in the mod (and there was Z-Fighting on every single entity unfortunately) has been resolved through a revamp of said models for the 100,000 downloads milestone (i got burnt out so i never was able to clean everything up in time)

No screenshots for the Z-Fighting as I wish for that to be more a surprise!

![2024-06-21_08 25 46](https://github.com/decodinatorX/Liroth-Revamped-Forge/assets/16389833/db94d7fc-8bd2-4c8c-abaf-5a154a2a63fe)
![2024-06-21_08 26 14](https://github.com/decodinatorX/Liroth-Revamped-Forge/assets/16389833/2ace9b86-734b-4fc9-889e-b586058e1a81)
![2024-06-21_08 26 17](https://github.com/decodinatorX/Liroth-Revamped-Forge/assets/16389833/dad53db8-9ddb-44e2-ac85-a06dfe8b014b)


These have been resolved in the current dev build and shall be pushed to 1.19.2 to 1.20.1 soon!
Thank you for your report and patience!

**Comment by Reshy** [comment] 2024-06-22 06:57
Thanks for the hard work!

**Comment by decodinatorX** [comment] 2024-06-23 13:31
Latest build fixes this issue!

**Closed as completed by decodinatorX** 2024-06-23 13:31 UTC
Labels: bug
